### ISSUE TITLE
Playlist folders are not supported

### ISSUE THREAD

**Issue by TechnicBRICKs** [BenediktAlkin/SongTaggerForSpotify#1]
When you say 'Playlist folders are not supported' / 'Existing playlists can only be viewed unorganized', does it means that song I've from playlists organized in folders, will not be "seen" and do not appear in 'All' songs after I've run 'Sync Library'!?

When you say 'Generated playlists have to be moved manually to a folder if desired (_only required once_)', does it means that if I move a generated playlist into a folder, later if run the same generator, the result will go directly into the folder where I've put it before!?

**Comment by BenediktAlkin** [comment]
The "All" meta playlist contains everything in your library (liked songs, songs in liked playlists and tagged songs that are no longer in your liked songs or in liked playlists). 

Yes exactly. When you run a generator it changes the existing playlist, independent of which folder it is in, but a generator can't put it into folders since that is not supported. So if you generate a playlist "pop" it will be created in the root folder of your playlists. If you then move it to say a "GenrePlaylist" folder and run the playlist generator again, the generator will update the playlist and it will stay in the "GenrePlaylist" folder.

I updated in readme to clarify this. Thanks for the feedback.
