### ISSUE TITLE
Song metadata not loading

### ISSUE THREAD

**Issue by morgannwash** [BenediktAlkin/SongTaggerForSpotify#11]
Hi! Just updated the song tagger and ran into an issue accessing song metadata. 

In the Song Metadata tab, info doesn't appear, even after resyncing library.
![issue](https://user-images.githubusercontent.com/101956407/162038051-9f38872a-542f-4ec1-af20-46119df37851.png)

In the Playlist Generator tab, a song's genres aren't viewable; a drop down doesn't appear when the filter is clicked.
![issue2](https://user-images.githubusercontent.com/101956407/162038054-d960f19a-7258-4fa5-8af0-98e5c59d59ea.png)

**Comment by BenediktAlkin** [comment]
Hi, make sure to press the Sync Library button. As the previous version didn't support metadata, it has to sync all the existing songs with the spotify metadata once. Everything you add to your library after the new update will be automatically updated.
After syncing, the metadata should be shown as intended in the Metadata viewer and also in the Playlist Generator.

Thanks for pointing that out, kinda forgot to make a hint for that.

**Comment by morgannwash** [comment]
Hi, sorry for the late reply! Unfortunately this problem persists even after syncing my library, restarting the Spotify desktop client, and restarting the program.

**Comment by BenediktAlkin** [comment]
I just double checked creating the database on the old version (v1.1.3) and then syncing it with the new version (v1.2.1) and it works just as expected.

What version are you running (displayed on the bottom of the start page)?

Could you share your database file so that I can try to reproduce the issue (your database file only contains information about songs, no personal information besides your username in the name of the file)?

**Comment by BenediktAlkin** [comment]
Thanks!

I managed to reproduce it and fixed it. Turns out some songs don't actually have metadata, which caused the issue. Somewhere around 4 songs out of 14000.
